"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const norm=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").trim();
const words=s=>norm(s).split(" ").filter(Boolean);
const NAME={mate:"Matematică",ro:"Limba română"};
function show(){const p=(location.hash||"#acasa").slice(1),page=["acasa","asistent","agenda"].includes(p)?p:"acasa";$$('.page').forEach(x=>x.hidden=x.id!==page);$$('nav a').forEach(a=>a.classList.toggle('on',a.dataset.p===page));scrollTo(0,0)}addEventListener('hashchange',show);show();

/* Asistent local: numai cuvinte-cheie și prefixe, fără AI/API. */
const KNOW={mate:{"Mulțimi și operații cu mulțimi":"Recunoaște relațiile dintre mulțimi și operațiile reuniune, intersecție și diferență.","Intervale numerice":"Reprezintă intervalele pe axa numerelor și efectuează reuniunea sau intersecția lor.","Divizibilitatea în ℕ":"Folosește criteriile de divizibilitate, descompunerea în factori primi, c.m.m.d.c. și c.m.m.m.c.","Ecuația de gradul II":"Aplică algoritmii de rezolvare prevăzuți pentru ecuații și inecuații; verifică soluția în mulțimea cerută.","Relații metrice, Pitagora, trigonometrie":"În triunghiul dreptunghic identifică datele, relațiile metrice și rapoartele trigonometrice potrivite.","Corpuri geometrice, arii și volume":"Identifică corpul și elementele metrice necesare înainte de a calcula aria sau volumul."},ro:{"Receptarea textului: idee, temă, tipuri de text":"Identifică informațiile importante, tema și ideile principale sau secundare, raportându-te la text.","Textul narativ":"Urmărește acțiunea, timpul, spațiul, autorul, naratorul și personajele, așa cum apar în text.","Versificație":"Recunoaște rima, strofa, măsura versurilor și ritmul, în contextul textului poetic.","Fraza":"Deosebește coordonarea de subordonare și aplică normele de punctuație cerute.","Funcții sintactice":"Identifică funcția sintactică și realizarea ei, apoi verifică acordul și punctuația.","Ortoepie și ortografie":"Aplică regulile de scriere și pronunție, folosind și contextul cuvântului.","Vocabular":"Stabilește sensul în context și recunoaște relațiile semantice ori mijloacele de îmbogățire a vocabularului."}};
const IDX={};for(const s in DATA)IDX[s]=DATA[s].map((r,i)=>({id:i,d:r[0],t:r[1],c:r[3]||"",k:r[2].split(',').map(words).filter(k=>k.length)}));
function keywordScore(q,k){const match=k.filter(x=>q.some(y=>y.startsWith(x)||x.startsWith(y)));return match.length===k.length?k.reduce((n,x)=>n+x.length,0):0}
function search(question,subject){const q=words(question);return q?IDX[subject].map(r=>({r,sc:Math.max(...r.k.map(k=>keywordScore(q,k)),0)})).filter(x=>x.sc).sort((a,b)=>b.sc-a.sc||a.r.t.localeCompare(b.r.t,'ro')).slice(0,5):[]}
function bubble(cls,text){const p=document.createElement('p');p.className=cls;p.textContent=text;$('#log').append(p)}
let subj='mate';function card(item){const d=document.createElement('article');d.className='res';const h=document.createElement('h3');h.textContent=item.t;d.append(h);const domain=document.createElement('small');domain.textContent=item.d;d.append(domain);if(item.c){const cs=document.createElement('small');cs.textContent='Competențe: '+item.c;d.append(cs)}const tip=KNOW[subj]?.[item.t]||'Recunoaște noțiunea în exerciții și aplic-o în contextul cerinței.';const p=document.createElement('p'),b=document.createElement('strong');p.className='know';b.textContent='Ce să știi: ';p.append(b,tip);d.append(p);$('#log').append(d)}
function ask(){const input=$('#q'),question=input.value.trim();if(!question)return;bubble('me',question);input.value='';const hit=search(question,subj);if(hit.length){bubble('bot','Apare în programa de '+NAME[subj]+'. Iată noțiunile potrivite:');hit.forEach(x=>card(x.r))}else{const other=subj==='mate'?'ro':'mate';bubble('bot',search(question,other).length?'Nu am găsit la '+NAME[subj]+', dar există potriviri la '+NAME[other]+'. Schimbă materia și caută din nou.':'Nu am găsit o potrivire în cuvintele-cheie. Încearcă termenul din programă, un sinonim sau un cuvânt mai scurt.')}$('#log').lastElementChild.scrollIntoView({block:'nearest'})}
$$('.tab').forEach(btn=>btn.onclick=()=>{subj=btn.dataset.s;$$('.tab').forEach(b=>{const on=b===btn;b.classList.toggle('on',on);b.setAttribute('aria-selected',on)});$('#q').focus()});$('#go').onclick=ask;$('#q').onkeydown=e=>{if(e.key==='Enter')ask()};$('#clear-chat').onclick=()=>{$('#log').replaceChildren();bubble('bot','Conversația a fost resetată. Scrie o noțiune nouă.');$('#q').value='';$('#q').focus()};

const KEY='en8_agenda_v1',ST={nou:'Nou',repet:'De repetat',stiu:'Știu'};let A={f:[],cur:null};try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&Array.isArray(saved.f))A=saved}catch(e){}const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(A))}catch(e){alert('Nu pot salva agenda în acest browser.')}};const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);const make=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e};const validAgenda=x=>x&&Array.isArray(x.f)&&x.f.every(f=>typeof f.id==='string'&&typeof f.n==='string'&&Array.isArray(f.notes));
function renderAgenda(){const folders=$('#folders'),notes=$('#notes');folders.replaceChildren();notes.replaceChildren();A.f.forEach(f=>{const b=make('button',f.n,'fo'+(f.id===A.cur?' on':''));b.type='button';b.onclick=()=>{A.cur=f.id;save();renderAgenda()};folders.append(b)});const f=A.f.find(x=>x.id===A.cur);if(!f){notes.append(make('p',A.f.length?'Alege un folder pentru a vedea notițele.':'Creează primul folder, de exemplu „Geometrie”.','note'));return}const head=make('div',undefined,'agenda-head'),title=make('h2',f.n),filter=document.createElement('input');filter.type='search';filter.className='agenda-search';filter.placeholder='Caută în notițele acestui folder';filter.setAttribute('aria-label','Caută în notițele acestui folder');head.append(title,filter);notes.append(head);const ta=document.createElement('textarea');ta.placeholder='Ce ai învățat sau ce trebuie să repeți?';ta.setAttribute('aria-label','Notiță nouă');const sel=document.createElement('select');for(const k in ST){const o=make('option',ST[k]);o.value=k;sel.append(o)}const add=make('button','Salvează notița','btn');add.type='button';add.onclick=()=>{const t=ta.value.trim();if(!t)return;f.notes.unshift({id:uid(),t,s:sel.value,d:new Date().toLocaleDateString('ro-RO')});save();renderAgenda()};const delFolder=make('button','Șterge folderul','btn danger');delFolder.type='button';delFolder.onclick=()=>{if(confirm('Ștergi folderul „'+f.n+'” și toate notițele?')){A.f=A.f.filter(x=>x!==f);A.cur=A.f[0]?.id||null;save();renderAgenda()}};const row=make('div',undefined,'row');row.append(sel,add,delFolder);notes.append(ta,row);const renderNotes=()=>{notes.querySelectorAll('.nt,.empty-search').forEach(x=>x.remove());const q=norm(filter.value);let count=0;f.notes.forEach(n=>{if(q&&!norm(n.t).includes(q))return;count++;const c=make('article',undefined,'nt '+(ST[n.s]?n.s:'nou'));c.append(make('p',n.t),make('small',(ST[n.s]||ST.nou)+' · '+n.d));const actions=make('div',undefined,'row');Object.keys(ST).filter(k=>k!==n.s).forEach(k=>{const b=make('button','→ '+ST[k]);b.type='button';b.onclick=()=>{n.s=k;save();renderAgenda()};actions.append(b)});const x=make('button','Șterge');x.type='button';x.onclick=()=>{f.notes=f.notes.filter(y=>y!==n);save();renderAgenda()};actions.append(x);c.append(actions);notes.append(c)});if(!count&&f.notes.length)notes.append(make('p','Nu există notițe care să conțină această căutare.','note empty-search'))};filter.oninput=renderNotes;renderNotes()}
$('#addf').onclick=()=>{const input=$('#fname'),n=input.value.trim();if(!n)return;const f={id:uid(),n,notes:[]};A.f.push(f);A.cur=f.id;input.value='';save();renderAgenda()};$('#fname').onkeydown=e=>{if(e.key==='Enter')$('#addf').click()};$('#exporta').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(A,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='agenda-en8.json';a.click();URL.revokeObjectURL(url)};$('#importa').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(!validAgenda(imported))throw Error();if(confirm('Importul va înlocui agenda actuală. Continui?')){A=imported;A.cur=A.f.some(f=>f.id===A.cur)?A.cur:(A.f[0]?.id||null);save();renderAgenda()}}catch(err){alert('Fișierul nu are formatul corect pentru agenda EN VIII.')}e.target.value=''};reader.readAsText(file,'utf-8')};renderAgenda();
