// STRAT DATE: [domeniu, titlu, "cuvinte-cheie separate prin virgulă", competențe]
// Sursa conținuturilor: textul tipărit din programele EN (Monitorul Oficial 842 bis/29.VIII.2022).
const DATA={
mate:[
["Mulțimi. Numere › Mulțimi","Mulțimi: descriere, notații și reprezentări","multime,multimi,notatie,reprezentare,element,apartine,submultime,nenumerice,finite,infinite",""],["Mulțimi. Numere › Mulțimi","Mulțimi finite și cardinal","multime finita,multimi finite,cardinal,cardinalul unei multimi,numar de elemente",""],["Mulțimi. Numere › Mulțimi","Operații cu mulțimi","reuniune,intersectie,diferenta,operatii cu multimi,intersecția,reuniunea",""],["Mulțimi. Numere › Mulțimi","Intervale numerice","interval,intervale,axa numerelor,intersectia intervalelor,reuniunea intervalelor","VIII.CS2.1, VIII.CS3.1, VIII.CS5.1, VIII.CS6.1"],
["Mulțimi. Numere › Numere naturale","Scrierea, compararea și ordonarea numerelor naturale","numere naturale,comparare,ordonare,axa numerelor,citirea numerelor,aproximari,estimari","V.CS1.1, V.CS2.1, V.CS3.1"],["Mulțimi. Numere › Numere naturale","Adunarea și scăderea numerelor naturale","adunare,scadere,numere naturale,calcul","V.CS2.1, V.CS3.1"],["Mulțimi. Numere › Numere naturale","Înmulțirea, împărțirea și factorul comun","inmultire,impartire,impartirea cu rest,factor comun","V.CS2.1, V.CS3.1"],["Mulțimi. Numere › Numere naturale","Puteri și scriere în baza 2 sau 10","putere,puteri,exponent,patratul unui numar,baza 2,baza doi,baza 10","V.CS2.1, V.CS3.1"],["Mulțimi. Numere › Numere naturale","Ordinea operațiilor și paranteze","ordinea operatiilor,paranteze,rotunde,patrate,acolade","V.CS2.1, V.CS3.1"],["Mulțimi. Numere › Numere naturale","Metode aritmetice de rezolvare a problemelor","metoda reducerii la unitate,metoda comparatiei,metoda figurativa,mersului invers,falsei ipoteze,probleme aritmetice","V.CS6.1"],
["Mulțimi. Numere › Divizibilitate","Divizor și multiplu","divizor,divizori,multiplu,multipli,divizibilitate,divizibil","VI.CS1.1, VI.CS2.1"],["Mulțimi. Numere › Divizibilitate","Criterii de divizibilitate","criterii de divizibilitate,divizibil cu 2,divizibil cu 3,divizibil cu 5,divizibil cu 9,divizibil cu 10","VI.CS2.1"],["Mulțimi. Numere › Divizibilitate","Numere prime și compuse","numere prime,numar prim,numere compuse,numar compus,prime intre ele",""],["Mulțimi. Numere › Divizibilitate","C.m.m.d.c. și c.m.m.m.c.","cmmdc,cmmmc,c.m.m.d.c,c.m.m.m.c,cel mai mare divizor comun,cel mai mic multiplu comun,factori primi,descompunere","VI.CS3.1"],
["Mulțimi. Numere › Numere întregi","Numere întregi și modul","numere intregi,intregi,opusul,modul,axa numerelor,comparare intregi","VI.CS1.3, VI.CS2.3, VI.CS3.3"],["Mulțimi. Numere › Numere raționale","Fracții ordinare și procente","fractie,fractii,procent,procente,subunitare,echiunitare,supraunitare,echivalente","V.CS1.2, V.CS2.2, V.CS3.2"],["Mulțimi. Numere › Numere raționale","Amplificarea, simplificarea și numitorul comun","amplificare,simplificare,ireductibila,numitor comun,aducerea la numitor","V.CS2.2, V.CS3.2"],["Mulțimi. Numere › Numere raționale","Fracții zecimale și periodicitate","zecimale,fractie zecimala,periodic,periodicitate,transformare fractie","V.CS1.2, V.CS2.2, V.CS3.2"],["Mulțimi. Numere › Numere raționale","Numere raționale","numere rationale,rational,rationale,opusul unui numar rational,modul,comparare rationale","VI.CS1.4, VI.CS2.4, VI.CS3.4"],["Mulțimi. Numere › Numere reale","Radicali și numere reale","numere reale,radical,radacina patrata,radacina,irational,iraționale,scoaterea factorilor,introducerea factorilor,rationalizare","VII.CS1.1, VII.CS2.1, VII.CS3.1"],["Mulțimi. Numere › Numere reale","Medii","media aritmetica,media ponderata,media geometrica,medie",""],
["Algebră › Calcul algebric","Calcul cu expresii algebrice","calcul algebric,expresie algebrica,termeni asemenea,reducerea termenilor","VIII.CS1.2, VIII.CS2.2, VIII.CS5.2"],["Algebră › Calcul algebric","Formule de calcul prescurtat","formule de calcul prescurtat,diferenta de patrate,patratul sumei,patratul diferentei","VIII.CS2.2, VIII.CS3.2"],["Algebră › Ecuații și inecuații","Ecuații și inecuații","ecuatie,ecuatii,inecuatie,inecuatii,necunoscuta,necunoscut","VIII.CS3.1, VIII.CS3.2, VIII.CS6.2"],["Algebră › Ecuații și inecuații","Sisteme de ecuații liniare","sistem,sisteme,ecuatii liniare,substitutie,reducerii","VII.CS1.2, VII.CS2.2, VII.CS3.2"],["Algebră › Ecuații și inecuații","Ecuația de gradul al II-lea","gradul 2,gradul ii,gradul doi,ecuatia de gradul,discriminant,delta","VIII.CS3.2, VIII.CS6.2"],["Algebră › Funcții","Funcții și reprezentări","functie,functii,grafic,graficul,dependente functionale,tabel,formula","VIII.CS1.3, VIII.CS2.3, VIII.CS3.3"],
["Organizarea datelor › Rapoarte","Rapoarte și proporții","raport,rapoarte,proportie,proportii,proprietatea fundamentala,proportii derivate,sir de rapoarte","VI.CS1.2, VI.CS2.2, VI.CS3.2"],["Organizarea datelor › Rapoarte","Mărimi direct sau invers proporționale","direct proportionale,invers proportionale,regula de trei simpla","VI.CS1.2, VI.CS3.2, VI.CS6.2"],["Organizarea datelor › Statistică","Tabele, grafice și diagrame","tabele,grafice,diagrame,statistica,frecventa,poligonul frecventelor","VII.CS1.3, VII.CS2.3"],["Organizarea datelor › Statistică","Indicatori statistici și probabilități","medie,mediana,mod,amplitudine,probabilitate,probabilitati","VII.CS2.3"],
["Geometrie › Noțiuni fundamentale","Puncte, drepte și segmente","punct,puncte coliniare,dreapta,semidreapta,segment,mijloc,simetric","V.CS1.3, V.CS2.3"],["Geometrie › Noțiuni fundamentale","Unghiuri","unghi,unghiuri,opuse la varf,adiacente,complementare,suplementare,bisectoare","VI.CS1.5, VI.CS2.5"],["Geometrie › Noțiuni fundamentale","Drepte paralele și perpendiculare","paralele,paralelism,perpendiculare,perpendicular,secanta,mediatoarea,distanta de la un punct la o dreapta","VI.CS2.5, VI.CS3.5"],["Geometrie › Triunghi","Triunghiul și liniile importante","triunghi,perimetru,unghi exterior,bisectoare,mediana,inaltime,mediatoare,cerc inscris,circumscris","VI.CS1.6, VI.CS2.6, VI.CS6.6"],["Geometrie › Triunghi","Congruența triunghiurilor","congruenta,congruente,criterii de congruenta,lul,ulu,lll","VI.CS3.6"],["Geometrie › Triunghi","Triunghiuri particulare","isoscel,echilateral,dreptunghic,ipotenuza,cateta,unghi de 30","VI.CS3.6, VII.CS1.7"],["Geometrie › Triunghi","Teorema lui Thales și segmente proporționale","thales,teorema lui thales,segmente proportionale,reciproca teoremei",""],["Geometrie › Triunghi","Asemănarea triunghiurilor","asemanare,asemenea,triunghiuri asemenea,criterii de asemanare,raportul ariilor","VII.CS1.6, VII.CS2.6, VII.CS3.6"],["Geometrie › Triunghi","Pitagora și relații metrice","pitagora,teorema catetei,teorema inaltimii,proiectii ortogonale,relatii metrice","VII.CS2.7, VII.CS3.7, VII.CS6.7"],["Geometrie › Triunghi","Trigonometrie în triunghiul dreptunghic","sinus,cosinus,tangenta,cotangenta,trigonometrie","VII.CS2.7"],["Geometrie › Patrulatere","Patrulatere","patrulater,paralelogram,dreptunghi,romb,patrat,trapez,linia mijlocie","VII.CS1.4, VII.CS2.4, VII.CS3.4"],["Geometrie › Cerc","Cercul și poligoanele regulate","cerc,coarda,diametru,raza,arc de cerc,unghi la centru,unghi inscris,tangenta,poligoane regulate","VII.CS1.5, VII.CS2.5, VII.CS3.5"],["Geometrie › Corpuri geometrice","Corpuri, arii și volume","corp,prisma,piramida,cub,paralelipiped,cilindru,con,sfera,arie laterala,arie totala,volum","VIII.CS1.5, VIII.CS2.5, VIII.CS3.5"],["Geometrie › Spațiu","Paralelism și perpendicularitate în spațiu","drepte in spatiu,plane paralele,plan perpendicular,dreapta perpendiculara pe plan,unghi diedru,teorema celor trei perpendiculare","VIII.CS1.4, VIII.CS3.4, VIII.CS5.4"]
],
ro:[
["Lectură","Idee, temă și plan de idei","cuvinte cheie,idee principala,idee secundara,tema,plan simplu,plan dezvoltat","1.1"],["Lectură","Text narativ","narativ,naratiune,narator,autor,personaj,actiune,timp,spatiu,momentele subiectului,persoana i,persoana a iii a,banda desenata","1.3"],["Lectură","Text descriptiv","descriptiv,descriere,text descriptiv","1.3"],["Lectură","Text dialogat și interviu","dialog,dialogat,interviu,dialogul","1.3"],["Lectură","Text explicativ","explicativ,text explicativ","1.3"],["Lectură","Text argumentativ","argumentativ,argument,text argumentativ,argumentare","1.8, 2.2"],["Lectură","Versificație","versificatie,rima,strofa,masura versurilor,ritm,vers",""],["Lectură","Text epic, liric și dramatic","epic,liric,dramatic,text dramatic,indicatii scenice,arta spectacolului,personaj dramatic,actori,decor,costume",""],["Lectură","Strategii de comprehensiune","inferenta,inferente,predictie,predictii,cauza efect,problema solutie,impresii de lectura,compararea textelor","1.2, 1.6"],["Lectură","Limbaj figurat și interpretare","personificare,comparatie,epitet,enumeratie,repetitie,metafora,aliteratie,hiperbola,antiteza,limbaj figurat,mesaj,interpretari multiple","1.4, 1.8"],
["Redactare","Etapele scrierii","etapele scrierii,generarea ideilor,planificarea,scrierea,rescrierea,corectarea greselilor","2.1, 2.4"],["Redactare","Părțile și organizarea textului","introducere,cuprins,incheiere,paragraf,paragrafe,asezarea in pagina,adecvarea la tema","2.1, 2.3"],["Redactare","Rezumat și vorbire indirectă","rezumat,vorbire directa,vorbire indirecta,transformarea vorbirii","2.1"],["Redactare","Tipare de redactare","pro contra,intrebarile jurnalistului,comparatie,analogie,narativ,descriptiv,dialogat,explicativ","2.1, 2.3"],["Redactare","Scrisoare, e-mail, jurnal și opinie","scrisoare,e mail,email,jurnal,preferinte,opinii,caracterizarea personajului","2.1, 2.3"],["Redactare","Etica redactării și stil","originalitate,etica redactarii,proprietatea termenilor,puritate,adecvare,naturalete,eufonie,concizie,corectitudine","2.4, 2.5"],
["Gramatică","Enunțul","enunt,asertiv,interogativ,exclamativ,imperativ,eliptic,afirmativ,negativ","3.1"],["Gramatică","Propoziția simplă și dezvoltată","propozitie simpla,propozitie dezvoltata,propozitie,norme de punctuatie","3.1"],["Gramatică","Fraza: coordonare și subordonare","fraza,coordonare,juxtapunere,jonctiune,conjunctii,subordonare,pronume relative,adverbe relative","3.2"],["Gramatică","Construcții sintactice","constructii active,constructii pasive,a fi,constructii impersonale,pronume reflexive,constructii incidente,concesive,conditionale","3.2"],["Gramatică","Predicat și subiect","predicat verbal,predicat nominal,nume predicativ,subiect,subiect neexprimat,acord","3.1, 3.2"],["Gramatică","Atribut, apoziție și complement","atribut,apozitie,complement,complement direct,complement indirect,complement prepozitional","3.1, 3.2"],["Gramatică","Circumstanțiale și topică","circumstantial,circumstantialul de mod,de timp,de loc,cauza,scop,topica","3.1, 3.2"],["Gramatică","Propoziții subordonate","atributiva,completiva directa,completiva indirecta,completiva prepozitionala,circumstantiala,cauzala,finala","3.2"],["Gramatică","Verbul","verb,verbul,moduri verbale,indicativ,imperativ,conjunctiv,conditional,optativ,timpuri,auxiliar,copulativ","3.1, 3.2"],["Gramatică","Forme verbale nepersonale","infinitiv,gerunziu,participiu,supin,forme nepersonale","3.1, 3.2"],["Gramatică","Prepoziția","prepozitie,prepozitia","3.1"],["Gramatică","Substantivul și articolul","substantiv,substantivul,gen,numar,caz,comun,propriu,colectiv,defectiv,vocativ,articol","3.1"],["Gramatică","Pronumele","pronume,pronumele,personal,politete,reflexiv,posesiv,demonstrativ,interogativ,relativ,nehotarat,negativ,clitice","3.1"],["Gramatică","Adjectivul","adjectiv,adjectivul,grade de comparatie,articol demonstrativ,adjectiv participial,acordul adjectivului","3.1"],["Gramatică","Adverbul","adverb,adverbul,adverbe de mod,de timp,de loc,grade de comparatie","3.1"],["Gramatică","Numeralul","numeral,numeralul,cardinal,ordinal","3.1"],["Gramatică","Interjecția","interjectie,interjectia,onomatopee,interjectia predicativa","3.1"],
["Ortoepie și ortografie","Alfabet, dicționar și sunete","alfabet,dictionar,articol de dictionar,vocala,consoana,semivocala,sunet litera","3.4"],["Ortoepie și ortografie","Diftong, triftong, hiat și silabă","diftong,triftong,hiat,silaba,despartirea in silabe,accent","3.4"],["Ortoepie și ortografie","Cuvinte de origine străină","cuvinte straine,origine straina,pronuntie,ortografie,ortoepie","3.4"],
["Vocabular","Sensul cuvântului și contextul","sens propriu,sens figurat,sens de baza,sens secundar,context,polisemantice","3.1"],["Vocabular","Relații semantice","sinonim,sinonime,antonim,antonime,omonim,omonime,camp lexical","3.1"],["Vocabular","Îmbogățirea vocabularului","derivare,compunere,conversiune,familie lexicala,imprumuturi,locutiuni,cuvinte compuse","3.1"],["Vocabular","Paronime și pleonasm","paronime,paronim,pleonasm","3.1"],
["Variație stilistică","Normă, abatere și registre","limba standard,norma,abatere,limba vorbita,limba scrisa,limbaj popular,regionala,registru,jargon,argou,colocvial,cultivat","3.5, 3.6"],["Variație stilistică","Coerența textului","succesiunea ideilor,timpurilor verbale,anafore,organizarea coerenta","3.6"],["Interculturalitate","Identitate și diversitate culturală","identitate,diversitate culturala,mitologie,carte romaneasca,prima carte tiparita,carte digitala,legende greco romane,literatura universala,valori etice,noi si ceilalti,limba romana in europa,comunitatea lingvistica,contacte culturale","4.1, 4.2, 4.3, 4.4"]
]};

// Detalieri suplimentare, păstrând același format de înregistrare.
DATA.mate.push(
["Mulțimi. Numere › Numere naturale","Împărțirea cu rest","impartire cu rest,deimpartit,impartitor,cat,rest",""],
["Mulțimi. Numere › Divizibilitate","Proprietăți ale divizibilității","proprietati ale divizibilitatii,divizibilitate",""],
["Mulțimi. Numere › Numere întregi","Operații cu numere întregi","adunarea numerelor intregi,scaderea numerelor intregi,inmultirea numerelor intregi,impartirea numerelor intregi,puteri intregi","VI.CS2.3, VI.CS3.3"],
["Mulțimi. Numere › Numere raționale","Operații cu fracții ordinare","adunarea fractiilor,scaderea fractiilor,inmultirea fractiilor,impartirea fractiilor,fractii ordinare","V.CS2.2, V.CS3.2"],
["Mulțimi. Numere › Numere raționale","Fracții și unități de măsură","fractii,unitati de masura,lungime,arie,volum,capacitate,masa,timp,unitati monetare","V.CS6.2"],
["Mulțimi. Numere › Numere raționale","Operații cu numere raționale","adunarea numerelor rationale,scaderea numerelor rationale,inmultirea numerelor rationale,impartirea numerelor rationale,puterea cu exponent intreg","VI.CS3.4, VI.CS6.4"],
["Mulțimi. Numere › Numere reale","Modulul și reprezentarea numerelor reale","modulul unui numar real,modul,reprezentarea numerelor reale,compararea numerelor reale","VII.CS1.1, VII.CS2.1"],
["Mulțimi. Numere › Numere reale","Operații cu numere reale","adunare numere reale,scadere numere reale,inmultire numere reale,impartire numere reale,puteri","VII.CS2.1, VII.CS3.1"],
["Algebră › Calcul algebric","Fracții algebrice","fractii algebrice,fractie algebrica",""],
["Algebră › Ecuații și inecuații","Inecuații în mulțimea numerelor reale","inecuatie,inecuatii,intervale,solutia inecuatiei","VIII.CS3.1, VIII.CS6.1"],
["Algebră › Funcții","Sistem de axe ortogonale","sistem de axe,axe ortogonale,abscisa,ordonata,coordonate",""],
["Algebră › Funcții","Distanța dintre două puncte","distanta dintre doua puncte,coordonate,plan cartezian",""],
["Organizarea datelor › Statistică","Frecvență, mediană, mod și amplitudine","frecventa,mediana,mod,amplitudine","VII.CS2.3"],
["Geometrie › Noțiuni fundamentale","Unități de măsură și transformări","unitati de masura,transformari de unitati,lungime,arie,volum","V.CS1.3, V.CS2.3"],
["Geometrie › Noțiuni fundamentale","Plan, semiplan și semidreaptă","plan,semiplan,semidreapta",""],
["Geometrie › Noțiuni fundamentale","Măsura unghiurilor","grade,minute sexagesimale,masura unghiului,unghi drept,ascutit,obtuz","VI.CS2.5"],
["Geometrie › Noțiuni fundamentale","Simetria față de o dreaptă","simetria fata de o dreapta,simetric,mediatoare","VI.CS3.5"],
["Geometrie › Triunghi","Inegalități în triunghi","inegalitati,inegalitatea triunghiului,triunghi",""],
["Geometrie › Triunghi","Cercul înscris și circumscris","cerc inscris,cerc circumscris,centrul cercului","VI.CS1.6, VI.CS2.6"],
["Geometrie › Triunghi","Centrul de greutate","centrul de greutate,mediane,triunghi",""],
["Geometrie › Patrulatere","Aria și perimetrul patrulaterelor","aria patrulaterului,perimetrul patrulaterului,aria trapezului,aria rombului","VII.CS3.4"],
["Geometrie › Cerc","Lungimea cercului și aria discului","lungimea cercului,aria discului,disc","VII.CS3.5"],
["Geometrie › Corpuri geometrice","Desfășurări și secțiuni","desfasurare,sectiune,sectiuni,corp geometric","VIII.CS2.4"],
["Geometrie › Corpuri geometrice","Piramidă și tetraedru","piramida,tetraedru,arie,volum","VIII.CS1.5, VIII.CS2.5"],
["Geometrie › Corpuri geometrice","Prismă, paralelipiped și cub","prisma,paralelipiped,cub,arie,volum","VIII.CS1.5, VIII.CS2.5"],
["Geometrie › Corpuri geometrice","Cilindru, con și sferă","cilindru,con,sfera,arie,volum","VIII.CS1.5, VIII.CS2.5"],
["Geometrie › Spațiu","Distanțe în spațiu","distanta de la un punct la un plan,distanta,drepte in spatiu,plane","VIII.CS3.4, VIII.CS5.4"],
["Geometrie › Spațiu","Unghiul dintre dreaptă și plan","unghiul dintre dreapta si plan,unghi diedru,plan","VIII.CS3.4"]
);
DATA.ro.push(
["Lectură","Texte continue, discontinue și multimodale","texte continue,texte discontinue,text multimodal,multimodal","1.1, 1.2, 1.3"],
["Lectură","Mijloace de caracterizare","mijloace de caracterizare,caracterizare,personaj","1.3"],
["Lectură","Răspuns afectiv și dezbatere","raspuns afectiv,dezbateri,argumentarea punctului de vedere","1.4, 1.8"],
["Redactare","Comentarea unui pasaj și descrierea emoției","comentarea pasajului,descrierea unei emotii,emotie","2.1, 2.3"],
["Gramatică","Punctuația frazei","virgula,punct si virgula,punctuatie,fraza","3.1, 3.2"],
["Gramatică","Acordul numelui predicativ","acordul numelui predicativ,nume predicativ,acord","3.1"],
["Gramatică","Acordul predicatului cu subiectul","acordul predicatului,subiect multiplu,subiect exprimat","3.1"],
["Gramatică","Tipuri de atribut","atribut,atribut adjectival,atribut substantival,atribut pronominal,atribut numeral,atribut adverbial","3.1"],
["Gramatică","Verbe copulative","verbe copulative,a fi,a deveni,a ajunge,a iesi,a se face,a parea,a ramane,a insemna","3.1, 3.2"],
["Gramatică","Pronume personal și de politețe","pronume personal,pronume de politete,flexiunea pronumelui,cazual","3.1"],
["Gramatică","Pronume reflexiv și pronume personal","pronume reflexiv,diferenta pronume reflexiv pronume personal","3.1"],
["Gramatică","Pronume posesiv și demonstrativ","pronume posesiv,adjectiv pronominal posesiv,pronume demonstrativ,adjectiv pronominal demonstrativ","3.1"],
["Gramatică","Pronume interogativ, relativ, nehotărât și negativ","pronume interogativ,pronume relativ,pronume nehotarat,pronume negativ,negatia","3.1"],
["Gramatică","Gradele de comparație ale adjectivului și adverbului","gradele de comparatie,adjectiv,adverb","3.1"],
["Ortoepie și ortografie","Corespondența sunet-literă","corespondenta sunet litera,sunet litera","3.4"],
["Ortoepie și ortografie","Variante accentuale","variante accentuale,accent,accent corect","3.4"],
["Vocabular","Cuvânt de bază, derivat și familie lexicală","cuvant de baza,cuvant derivat,familie lexicala","3.1"],
["Variație stilistică","Termeni științifici și diminutive","termeni stiintifici,diminutive,valori stilistice","3.5, 3.6"],
["Interculturalitate","Cultura populară și contacte culturale","cultura populara,relatii culturale,contacte culturale,valori culturale romanesti","4.1, 4.2, 4.3, 4.4"]
);
